"""customers partners sessions

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 14:38:29.911183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_family_id'), 'auth_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_subject_id'), 'auth_sessions', ['subject_id'], unique=False)
    op.create_table('price_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_default_partner', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_types')),
    sa.UniqueConstraint('external_id', name=op.f('uq_price_types_external_id'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.Enum('retail', 'partner', name='clientkind', native_enum=False, length=20), nullable=False),
    sa.Column('partner_status', sa.Enum('none', 'pending', 'approved', 'rejected', name='partnerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('kpp', sa.String(length=20), nullable=True),
    sa.Column('legal_address', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('price_type_id', sa.Integer(), nullable=True),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('manager_note', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_type_id'], ['price_types.id'], name=op.f('fk_customers_price_type_id_price_types'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('external_id', name=op.f('uq_customers_external_id'))
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_kind'), 'customers', ['kind'], unique=False)
    op.create_index(op.f('ix_customers_partner_status'), 'customers', ['partner_status'], unique=False)
    op.create_table('product_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_type_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_type_id'], ['price_types.id'], name=op.f('fk_product_prices_price_type_id_price_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices')),
    sa.UniqueConstraint('product_id', 'price_type_id', name=op.f('uq_product_prices_product_id'))
    )
    op.create_index(op.f('ix_product_prices_price_type_id'), 'product_prices', ['price_type_id'], unique=False)
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.add_column('order_items', sa.Column('price_kind', sa.String(length=20), nullable=False, server_default='retail'))
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('price_type_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_unique_constraint(op.f('uq_orders_external_id'), 'orders', ['external_id'])
    op.create_foreign_key(op.f('fk_orders_customer_id_customers'), 'orders', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_orders_price_type_id_price_types'), 'orders', 'price_types', ['price_type_id'], ['id'], ondelete='SET NULL')
    op.add_column('products', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(op.f('uq_products_external_id'), 'products', ['external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_products_external_id'), 'products', type_='unique')
    op.drop_column('products', 'external_id')
    op.drop_constraint(op.f('fk_orders_price_type_id_price_types'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('fk_orders_customer_id_customers'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('uq_orders_external_id'), 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'exported_at')
    op.drop_column('orders', 'external_id')
    op.drop_column('orders', 'price_type_id')
    op.drop_column('orders', 'customer_id')
    op.drop_column('order_items', 'price_kind')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_price_type_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_customers_partner_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_kind'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('price_types')
    op.drop_index(op.f('ix_auth_sessions_subject_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_family_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
